[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anna16"
version = "2.0.0"
description = "ANNA16 is an end-to-end tool that predicts 16S rRNA gene copy number (GCN) from 16S rRNA gene sequence."
license = "Apache-2.0"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
anna16 = ["model_files/*/*.pt", "model_files/*/*.pkl"]  # Include small model files if needed
